# Generated by Django 4.2 on 2023-04-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
