# Generated by Django 4.2 on 2023-05-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_useractivationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_posts',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
