# Generated by Django 4.2 on 2023-04-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialUser', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
