# Generated by Django 4.2 on 2023-05-01 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialUser', '0004_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-timestamp',)},
        ),
    ]
